server:
    port: 8080
    address: localhost

spring:
    profiles: dev
    datasource:
        # dataSourceClassName: org.h2.jdbcx.JdbcDataSource
        # url: jdbc:h2:mem:jhipster
        dataSourceClassName: org.postgresql.ds.PGSimpleDataSource
        url: jdbc:postgresql://ec2-54-225-182-133.compute-1.amazonaws.com/dekrmq10ij3nsl?user=nvmnxdpltcoasp&password=L93zT1195u5Kjaa5JoFFJILnXh&ssl=true&sslfactory=org.postgresql.ssl.NonValidatingFactory
        databaseName:
        serverName:
        username: nvmnxdpltcoasp
        password: L93zT1195u5Kjaa5JoFFJILnXh

    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        database: H2
        openInView: false
        show_sql: true
        generate-ddl: false
        hibernate:
            ddl-auto: none
            naming-strategy: org.hibernate.cfg.EJB3NamingStrategy
        properties:
            hibernate.cache.use_second_level_cache: true
            hibernate.cache.use_query_cache: false
            hibernate.generate_statistics: true
            hibernate.cache.region.factory_class: org.hibernate.cache.ehcache.SingletonEhCacheRegionFactory

    thymeleaf:
        mode: XHTML
        cache: false

metrics:
    jmx.enabled: true
    graphite:
        enabled: false
        host:
        port:

cache:
    timeToLiveSeconds: 3600
    ehcache:
        maxBytesLocalHeap: 16M

# You can add as many as folders to watch
# You just need to add a dash + the directory to watch
hotReload:
    enabled: true
    package:
      project: com.john_g_shultz.site
      domain: com.john_g_shultz.site.domain
      restdto: com.john_g_shultz.site.web.rest.dto
    liquibase:
      defaultCatalogName:
      defaultSchema: public
    watchdir:
      - target/classes
