server:
    port: 8080
    address: localhost

spring:
    profiles: prod
    datasource:
        # dataSourceClassName: org.h2.jdbcx.JdbcDataSource
        # url: jdbc:h2:mem:jhipster
        dataSourceClassName: org.postgresql.ds.PGSimpleDataSource
        url: jdbc:postgresql://ec2-54-225-182-133.compute-1.amazonaws.com/dekrmq10ij3nsl?user=nvmnxdpltcoasp&password=L93zT1195u5Kjaa5JoFFJILnXh&ssl=true&sslfactory=org.postgresql.ssl.NonValidatingFactory
        databaseName:
        serverName:
        username: nvmnxdpltcoasp
        password: L93zT1195u5Kjaa5JoFFJILnXh

    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        database: POSTGRESQL
        openInView: false
        show_sql: false
        generate-ddl: false
        hibernate:
            ddl-auto: none
            naming-strategy: org.hibernate.cfg.EJB3NamingStrategy
        properties:
            hibernate.cache.use_second_level_cache: true
            hibernate.cache.use_query_cache: false
            hibernate.generate_statistics: false
            hibernate.cache.region.factory_class: org.hibernate.cache.ehcache.SingletonEhCacheRegionFactory


    thymeleaf:
        mode: XHTML
        cache: true


metrics:
    jmx.enabled: true
    graphite:
        enabled: false
        host:
        port:

cache:
    timeToLiveSeconds: 3600
    ehcache:
        maxBytesLocalHeap: 256M
